import type { AppManifest } from "@corely/contracts";

export const workspacesAppManifest: AppManifest = {
  appId: "workspaces",
  name: "Workspaces",
  tier: 0,
  version: "1.0.0",
  description: "Workspace and profile management",
  dependencies: [],
  capabilities: [],
  permissions: [],
  menu: [
    {
      id: "workspace-settings",
      scope: "web",
      section: "workspace",
      labelKey: "nav.workspace",
      defaultLabel: "Workspace Settings",
      route: "/settings/workspace",
      icon: "Building",
      order: 90,
    },
    {
      id: "payment-methods-settings",
      scope: "web",
      section: "workspace",
      labelKey: "nav.paymentMethods",
      defaultLabel: "Payment Methods",
      route: "/settings/payment-methods",
      icon: "CreditCard",
      order: 91,
    },
    {
      id: "profile-settings",
      scope: "web",
      section: "profile",
      labelKey: "nav.profile",
      defaultLabel: "Account & Profile",
      route: "/settings",
      icon: "User",
      exact: true,
      order: 95,
    },
    {
      id: "workspace-members",
      scope: "web",
      section: "team",
      labelKey: "nav.members",
      defaultLabel: "Team & Members",
      route: "/settings/members",
      icon: "Users",
      order: 92,
    },
    {
      id: "workspace-roles",
      scope: "web",
      section: "roles",
      labelKey: "nav.roles",
      defaultLabel: "Roles & Permissions",
      route: "/settings/roles",
      icon: "ShieldAlert",
      order: 93,
    },
  ],
};
